USE Day1_SQL

CREATE TABLE employees
(
	Employee_Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(10) NOT NULL,
	LastName VARCHAR(10) NOT NULL,
	Email VARCHAR(20) NOT NULL,
	PhoneNumber NUMERIC(10) DEFAULT NULL,
	Hire_Date DATE NOT NULL,
	Job_Id INT NOT NULL FOREIGN KEY REFERENCES jobs(JobId),
	Salary NUMERIC(6) NOT NULL,
	Commission NUMERIC(4) DEFAULT NULL,
	Manager_Id int DEFAULT NULL ,
	Department_Id INT NOT NULL FOREIGN KEY REFERENCES department(department_id),
)
